### ISSUE TITLE
Copyright Issue -> Theme revamp

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#109]
**Content Rehaul Exhaustive List**
- [x] [Homepage](https://cryptocodeschool.in/tezos)
- [x] [Curriculum Overview](https://cryptocodeschool.in/tezos/overview)
- [x] plant -> robots
- [x] `Plant` contract becomes `Robot` contract
- [x] seed becomes gem
- [x] zombie -> alien
- [x] [up next view](https://cryptocodeschool.in/tezos/up-next/)
- [x] Game intro, game over(Success/Failure) modal
- [x] Robot Growth modal
- [x] SEO meta data plants/zombies -->  robots/aliens theme

**Graphic Rehaul(plants/zombies --> robots/aliens)**
- [x] Plant --> Robot Growth modal
- [x] (Up Next view) plant --> robot 
- [x] Game view: plant --> robot, zombies --> aliens
- [x] Homeview 
- [x] replace seed --> gem
- [x] logo

**Comment by bhaskarSingh** [comment]
Status update:
TODOS: Left, replacing theme logo & updating SEO meta image

**Comment by prastut** [comment]
## Landing page: 

![image](https://user-images.githubusercontent.com/10279686/82861556-b281ec00-9f3a-11ea-9bbe-cd5f5a17ac6a.png)
Replace this image

**Comment by bhaskarSingh** [comment]
UI Syncup with cryptoverse wars theme todos:

- [ ] Homeview
- [ ] overview
- [ ] learning interface
- [ ] up-next view
- [ ] storyline view
- [ ] gameview
