### ISSUE TITLE
Home Page "Start learning" button is unresponsive sometimes

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#123]
Before you submit, please add:

- [ ] **System Information**

  - [ ] Browser type and version
  - [ ] OS type and version
  - [ ] Any error messages in the JS console

- [ ] **Describe the bug**

  

- [ ] **To Reproduce**

- [ ] **Expected behavior**

- [ ] **Screenshots (optional)**

- [ ] **Additional context (optional)**

**Comment by prastut** [comment]
Probably an issue from Gatsby side: https://github.com/gatsbyjs/gatsby/issues/21193

**Comment by prastut** [comment]
Stale and non-relevant for Phase 2 of the platform.
