### ISSUE TITLE
Taquito module isn't executing code 

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#137]
On clicking `run code` for module-4. CORS blocked for https://api.tez.ie/keys/carthagenet/ error is being shown on the dev console.

![Screenshot 2020-11-23 at 3 45 35 PM](https://user-images.githubusercontent.com/16613455/99950699-f303da80-2da2-11eb-8e7c-bb6d24f3d88c.png)
 

Using `https://carthagenet.SmartPy.io` RPC should resolve the issue.

**Comment by bhaskarSingh** [comment]
![Screenshot 2020-11-25 at 10 29 01 PM](https://user-images.githubusercontent.com/16613455/100258987-b0422e00-2f6d-11eb-85a3-f76f8cf2b0ef.png)

carthagenet is obsolete now.

**Comment by prastut** [comment]
This is fixed as per @manangouhari
