### ISSUE TITLE
Authentication flow

### ISSUE THREAD

**Issue by manangouhari** [buidl-labs/crypto-code-school-inside-tezos#145]
**What's the motivation behind the feature? what problem does the feature intend to solve ?**
Implements the auth flow for the user.

**Comment by manangouhari** [comment]
Update for @bhaskarSingh - 
Close to completing this. All the UI is done. Half the logic is done. 
Will flesh out the rest in the morning, refactor, and push.

**Comment by manangouhari** [comment]
@bhaskarSingh apologies. This took way longer than expected. Have implemented the functionality now. Will test in the morning and raise a PR.

**Comment by manangouhari** [comment]
@bhaskarSingh kindly review this video which demonstrates the auth flow - https://drive.google.com/file/d/1hRWI8dn5XWgV7EOxoC7trUlarHeW5Km6/view?usp=sharing

**Comment by prastut** [comment]
Merging this issue in duplicate/favor of #152
