### ISSUE TITLE
Academy view todos

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#162]
- [x] Add interactive action from chapters 2 to 5 within the Basics of the blockchain module.

![Screenshot 2021-02-15 at 3 51 52 PM](https://user-images.githubusercontent.com/16613455/107935310-3ab39000-6fa7-11eb-95af-ac074d1098c8.png)

- [x] Redo button is broken, needs be to fixed. "Have a doubt" button is non-interactive, link cryptoverse support group channel to it. (https://t.me/joinchat/FA99PXywCizUbfE7)

**Comment by bhaskarSingh** [comment]
![Screenshot 2021-02-15 at 11 49 09 AM](https://user-images.githubusercontent.com/16613455/107934856-9598b780-6fa6-11eb-85f6-479c37f4f874.png)

- [ ] Compiled code is overflowing

**Comment by bhaskarSingh** [comment]
- [ ] Taquito's module code runner is broken. It's not showing the output.

**Comment by manangouhari** [comment]
- [ ] Run Code, and Show Answer buttons are cut-off in module-4.

**Comment by prastut** [comment]
@bhaskarSingh and @manangouhari are the todos mentioned on this thread fixed?

**Comment by manangouhari** [comment]
> @bhaskarSingh and @manangouhari are the todos mentioned on this thread fixed?

Apart from minor UI fixes, it's sorted.
