### ISSUE TITLE
SmartPy compiler not working.

### ISSUE THREAD

**Issue by manangouhari** [buidl-labs/crypto-code-school-inside-tezos#179]
Tested this for `FA2 tokens` module. The SmartPy code is correct and runs on the SmartPy ide, but our compiler gives an error and the code doesn't compile. 
Requesting @bhaskarSingh to take a look.

**Comment by manangouhari** [comment]
@bhaskarSingh are you looking into this?

**Comment by bhaskarSingh** [comment]
> @bhaskarSingh are you looking into this?

I have opened #181  PR. Please test & check whether the code is compiling correctly there or not.

**Comment by prastut** [comment]
Fixed as per @manangouhari
