### ISSUE TITLE
Sell & Withdraw cryptobot : Show warning in case balance is zero or insufficient

### ISSUE THREAD

**Issue by harsh242** [buidl-labs/crypto-code-school-inside-tezos#188]
**What's the motivation behind the feature? what problem does the feature intend to solve ?**
Show warning in case balance is zero or insufficient similar to `\transaction` in Sell & Withdraw from sell modal

**Describe the solution you'd like.**
![image](https://user-images.githubusercontent.com/49694914/109255516-23339d00-781a-11eb-9a33-f9964fb5e74e.png)
![image](https://user-images.githubusercontent.com/49694914/109255527-2b8bd800-781a-11eb-8262-70c1d1b08193.png)

cc @bhaskarSingh

**Comment by bhaskarSingh** [comment]
I have already implemented this feature.

**Comment by bhaskarSingh** [comment]
Ah! Got it. I will take lead here.
