### ISSUE TITLE
Cookie popup appears unexpectedly & then disappears.

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#191]
- [ ] **Expected behavior**
After I close the cookie popup. It should not show again but it does for a moment on every page view & then disappears.

- [ ] **Screenshots (optional)**

- [ ] **Additional context (optional)**
https://www.loom.com/share/51c4c69d1f374aa1b378ca0955bb8681

**Comment by manangouhari** [comment]
Can you please tell me this is on which branch?

**Comment by manangouhari** [comment]
I can't seem to replicate this.
https://www.loom.com/share/caa3682bfe8b44d0a112a5c5ab6cafd4

**Comment by bhaskarSingh** [comment]
Try this link https://develop.cryptocodeschool.in/tezos

Steps to reproduce the bug
1. Use brave/chrome browser & go to https://develop.cryptocodeschool.in/tezos link
2. Close the cookies pop-up
3. Refresh the page
4. You will see the behavior mentioned here https://www.loom.com/share/caa3682bfe8b44d0a112a5c5ab6cafd4

**Comment by manangouhari** [comment]
Yep, can see it now. Will fix.
