### ISSUE TITLE
Design and implement empty cryptobot page

### ISSUE THREAD

**Issue by manangouhari** [buidl-labs/crypto-code-school-inside-tezos#194]
**What's the motivation behind the feature? what problem does the feature intend to solve ?**
Design for the case when there's no cryptobot of a specific `token_id`

![image](https://user-images.githubusercontent.com/31039184/109431048-872cb000-7a2a-11eb-97ed-c2d904600cb7.png)

**Comment by harsh242** [comment]
Please check the Design: https://www.figma.com/file/eUQ3EIhaGW2N8CkTu6Ndnm/BUIDL-Labs---Tezos---Cryptoverse-Wars---Final-Designs?node-id=1883%3A0
@manangouhari 
Also, I'll implement it when the new crypto bot page will be merged with develop.
