### ISSUE TITLE
Copy update in claim-transaction flow

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#201]
![Screenshot 2021-03-02 at 4 51 38 PM](https://user-images.githubusercontent.com/16613455/109641468-bf8dd480-7b77-11eb-90d3-8a566d50ebf4.png)

Copy needs to be updated for claim-transaction & transaction file for when a bot is successfully acquired or bought.

**Comment by prastut** [comment]
Stale.
