### ISSUE TITLE
Implement Mobile view

### ISSUE THREAD

**Issue by harsh242** [buidl-labs/crypto-code-school-inside-tezos#212]
**What's the motivation behind the feature? what problem does the feature intend to solve ?**
Implement mobile view of the platform

**Describe the solution you'd like.**
Design:
[Link](https://www.figma.com/file/eUQ3EIhaGW2N8CkTu6Ndnm/BUIDL-Labs---Tezos---Cryptoverse-Wars---Final-Designs?node-id=1532%3A9515)

**Comment by prastut** [comment]
Implement a mechanism to retain users who are going to dropoff since the platform is not designed to be used on mobile.
