### ISSUE TITLE
Website load time is too slow.

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#219]
Currently, the SmartPy compiler starts loading on hitting the landing page which combined with all dependency is around 15Mb. 

**Solution**
Only load SmartPy compiler when needed that is in modules 3 & 4.

**Comment by harsh242** [comment]
The Loading time could be also slow due to the large videos we have on the landing page?
They are of 3 & 1 Mb

**Comment by manangouhari** [comment]
SmartPy compiler isn't the issue for the high load time. It's being loaded async.

**Comment by prastut** [comment]
Fixed as per @manangouhari
