### ISSUE TITLE
Academy - Differentiate headings and body text for content

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#229]
Currently, it's very hard to understand the difference between heading and body since both of them are white color.

**Comment by prastut** [comment]
@manangouhari take help from Aayush for color scheme. 

The exact issue is the readability of this page is not upto the mark: 

![image](https://user-images.githubusercontent.com/10279686/110790005-83085a00-8296-11eb-8301-030e33187dbc.png)

**Comment by aayushsaini1** [comment]
Body Text - `#CECECE`
font-size - '1.125rem'

Heading - '#FFFFFF'
font-size - '1.5rem'

Links - '#60A5FA'
underline so that links stand out.
