### ISSUE TITLE
Customizer - Critical Fixes for Reddit Launch

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#231]
- [x] Camera position is too high = bot it not in center.

Ref: Camera looks better (focal length, position) in buy cryptobot page as compared to customiser.

**Comment by bhaskarSingh** [comment]
> Selection of body parts is not perfect. Eg: face selection changes color of the base as well. Video link: https://www.loom.com/share/09bac4d5149e4be7a0b19ca508754572

@harsh242 Naming convention for body parts has been updated for the new 3D model. Please check the previous version of the model and keeping the naming convention the same as earlier would resolve this issue.

**Comment by harsh242** [comment]
@bhaskarSingh I the new 3D model only has floor as new name rest is exactly the same.
Please [Try it out here](https://deploy-preview-251--blissful-mcnulty-82f253.netlify.app/tezos/customizebot)
The color selection is still not perfect.

**Comment by bhaskarSingh** [comment]
>  Fix lighting being wonky sometimes issue.
Currently the customizer code is not waiting for lighting component to be loaded fully and proceeded ahead.
A solution might be to defer loading of the customizer till the lighting module is fixed.

@harsh242 Why can't we use default lighting provided by threejs?

**Comment by harsh242** [comment]
> Why can't we use default lighting provided by threejs?

Possible, I'll set up the lighting using the lighting provided by three js.
You can take up the other issues
