### ISSUE TITLE
Disable buttons when clicked.

### ISSUE THREAD

**Issue by manangouhari** [buidl-labs/crypto-code-school-inside-tezos#246]
I've ran through the whole simulation of claiming a cryptobot with two people so far. 
Both of them ended up clicking the button to confirm, twice - which opens up two confirm modals. 
This is because Temple is slow in responding with the pop-up which asks them to sign the transaction. 
Disabling the button when clicked, should prevent this behavior.

**Comment by manangouhari** [comment]
@harsh242 - will need input from design side over here. Prastut's suggestion was that Beacon opens up in the top right, which is out of our main line of vision, as the user is focused on the "Confirm" button. Even yesterday we saw this play out, Saumay clicked the "Confirm" button twice. Hence, when he rejected the second transaction, our UI showed him the whole confetti thingy. Need a solution to curb this behavior.

Let me know if you have any ideas around how we can solve for this.

**Comment by harsh242** [comment]
Recorded a [Loom Video](https://www.loom.com/share/04762ed691f44eb3a2fda277e15a2542) to show how the interaction will be when the user clicks on confirm. It is very similar to how it happens in the temple wallet.

Let me know if you have any doubts

**Comment by manangouhari** [comment]
Got ittt, sounds good. I had something similar in mind.
