### ISSUE TITLE
Display Cryptobot in mainstream wallets

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#248]
## Major
Is there a way to get Cryptobot added via a click similar to what happens in the Ethereum ecosystem: 

![image](https://user-images.githubusercontent.com/10279686/110791049-c911ed80-8297-11eb-9afa-5573dc8f9fc1.png)
- [ ] Temple Wallet

**Comment by bhaskarSingh** [comment]
Temple wallet is now automatically showing owned NFT.

![Screenshot 2021-03-16 at 9 00 57 PM](https://user-images.githubusercontent.com/16613455/111336000-d9143d80-869a-11eb-84a8-18f62c7b65e0.png)

**Comment by bhaskarSingh** [comment]
Contract deployed on mainnet permissionlessly shows up within both temple & kukai wallet.

Can be tested by simply owning an nft cryptobot & checking your temple/kukai wallet app. It will automatically show up there.
