### ISSUE TITLE
Module 0 Audit

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#249]
![image](https://user-images.githubusercontent.com/10279686/110792351-468a2d80-8299-11eb-8903-03755e7d6bd8.png)

@aayushsaini1

**Comment by manangouhari** [comment]
Completed by @aayushsaini1

**Comment by prastut** [comment]
@manangouhari I still see the same content as the above-screenshotted image here: 
https://develop.cryptocodeschool.in/tezos/academy/module-0

This doesn't seem to be fixed and from an experience PoV, this page is amongst the top pages that are going to be viewed the highest. 

(No hurry to solve this, you are on an off today, just FYin'g here for tomorrow)

**Comment by manangouhari** [comment]
Does this look better?

![image](https://user-images.githubusercontent.com/31039184/111062181-64d86f00-84cd-11eb-8590-00981262adaf.png)

**Comment by prastut** [comment]
No. Please take your time. 

Recommendation: 

Go through this flow: 

1. Landing Page
2. CTA to proceed to overview. 
3. CTA to proceed to Module 0

Are you able to make a coherent story with this copy that works well with all the environment of the page? 

=================

For eg: this copy doesn't have anything to relate with Cryptobots. 

The root cause that this copy is occurring is because you are treating the copy in isolation, but in fact it's part of the overall page/Module0/product.

**Comment by manangouhari** [comment]
Got ittt

**Comment by manangouhari** [comment]
I've come up with multiple examples. Let me know which one is the best, will further iterate on that one.

![image](https://user-images.githubusercontent.com/31039184/111064331-7162c480-84d9-11eb-88f1-45b2c819d6ab.png)

![image](https://user-images.githubusercontent.com/31039184/111064517-6f4d3580-84da-11eb-896f-b034dad78198.png)


![image](https://user-images.githubusercontent.com/31039184/111064637-221d9380-84db-11eb-95ed-c00b9677304d.png)

![image](https://user-images.githubusercontent.com/31039184/111064702-7c1e5900-84db-11eb-80e1-9bb6b70c4c93.png)

**Comment by prastut** [comment]
No example suffices. 

The questions that are going in users' mind which copy should ideally answer?  

- How do Cryptobots factor in the overall Cryptoverse Wars? 
- Hey I just saw this cool bot on Twitter, how do I get one of my own? 
- I am a blockchain noob, and I think blockchain is super hard to grasp. Can you prove me wrong? 

===========

Out of all the 4 examples, the third example works best. 

I have a feeling you are still trying to compile the code the same way, without understanding the root cause of why the code is breaking (analogy of why the copy isn't working). 😅

Pause. Go for a walk. 

And then place yourself inside the shoes of the user and try to navigate the platform from the landing page to end of module 0. 
See if you (as the user) have all the signs in order to proceed next. 

It's similar problem airport designers face. They design the airport but then they have to design the airport signs (exit, entry, path to toilets etc) without having the bias that they know the airport's blueprint at the back of the mind. 

Nothing is obvious to the user. Don't make them think. If they are thinking of what do I do next/where do I go next/why is this object here, you haven't done a good job as a designer.

**Comment by manangouhari** [comment]
Is this an improvement over the others?

![image](https://user-images.githubusercontent.com/31039184/111085491-92f59780-853d-11eb-9e61-eff25f58ee2b.png)

**Comment by prastut** [comment]
@manangouhari yup this looks good!
