### ISSUE TITLE
Minor Copy fixes 

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#265]
Documented problems here: 

https://www.loom.com/share/dd6d40c78ec445caab668862befc21cf

**Comment by manangouhari** [comment]
Tried something with the second section. Not sure how it looks tho.

![image](https://user-images.githubusercontent.com/31039184/111379435-260f0880-86c9-11eb-8c37-ca7d33158f35.png)
