### ISSUE TITLE
Proof Read entire copy

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#277]
## Problem Statement
![image](https://user-images.githubusercontent.com/10279686/111245897-615afa00-862b-11eb-84b8-d3a05e3c2b65.png)

## Possible solutions

- Don't do it manually. 

I have used the following solutions to help me catch errors that my eyes are overlooking: 
- Using any spell checker vs-code extension like this: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker&ssr=false

- Using Grammarly. Copying and pasting it to their app and then following their suggestions to improve. 
(I have a paid account, DM for credentials)

The interface change really helps eyes getting unconditioned and seeing errors.

**Comment by manangouhari** [comment]
> Using Grammarly. Copying and pasting it to their app and then following their suggestions to improve.
(I have a paid account, DM for credentials)


Should've seen this before 😢 
Ran the whole Module-0 through my free version of Grammarly today.
