### ISSUE TITLE
Cryptobot unique URL page design

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#278]
## Problem Statement: 

![image](https://user-images.githubusercontent.com/10279686/111251822-f82cb400-8635-11eb-88c4-1dcb2d0fd741.png)

This is what it looks like on my 27inch monitor. 

My reaction: 
THIS IS SO SAD, I WISH TO SEE THE BOT IN FULL GLORY

I actually ended up hacking CSS to see the bot in a bigger view: 

![image](https://user-images.githubusercontent.com/10279686/111251977-31fdba80-8636-11eb-9177-56e24fd4533f.png)

## Solution

 - [x] Add a full screen mode. 
 - [ ] Get the height and width of the model viewer to full screen height. 
 - [x] Make it auto-rotate slowly by default.

**Comment by harsh242** [comment]
>Get the height and width of the model viewer to full-screen height.

Looks a little wierd😅
![image](https://user-images.githubusercontent.com/49694914/112977693-facdf400-9173-11eb-81eb-c631137e6ca2.png)

**Comment by prastut** [comment]
@harsh242 yup same page. This page design needs to be thought of. I proposed a first jerk reaction idea. 

Instead of vertical tiling where cryptobot is kept on left and its' info in right, should we try horizontal tiling i.e cryptobot info in top and cryptobot in the bottom taking like 60% of the real estate?

**Comment by harsh242** [comment]
>Instead of vertical tiling where cryptobot is kept on left and its' info in right, should we try horizontal tiling i.e cryptobot info on top and cryptobot in the bottom taking like 60% of the real estate?

Yeah we can try horizontal tiling keeping the cryptobot first would also suffice, very similar to how foundation does (example here)[https://foundation.app/KatieTorn/lady-sphinx-cu-14665]

**Comment by prastut** [comment]
Ooh the Foundation link looks good and worth stealing (I checked it on
mobile and this as close to the experience I would want)

**Comment by harsh242** [comment]
@aayushsaini1 adding aayush to join the conversation
