### ISSUE TITLE
Marketplace not loading bots

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#341]
![image](https://user-images.githubusercontent.com/10279686/115653658-314ef700-a34d-11eb-9110-370b75f8f605.png)

**Comment by bhaskarSingh** [comment]
It seems to be working for me.

**Comment by prastut** [comment]
> Please share steps to reproduce if possible.
Disable cache through console and load it again. 

See a reproduction of the issue here: 
https://www.loom.com/share/b4f6b06a539d45898fccefdd14429909
