### ISSUE TITLE
Learning Interface UI subtle changes

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#50]
changes need to be made as described in [figma link](https://www.figma.com/file/hcoRbRF5fZREDTJkLl7cXk/BUIDL-for-Tezos?node-id=100%3A0)

**Comment by bhaskarSingh** [comment]
@AbhinavThukral97  does learning interface required any more changes

**Comment by prastut** [comment]
Closing since stale.
