### ISSUE TITLE
Way to report error/ask for help in relation to individual chapters content

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#53]
User should have the option to report error via the help button within the learning interface, for reporting discrepancy

**Comment by prastut** [comment]
## Generic Help: 

Generic help across the board leading to Telegram Group. (Make a Telegram Group)

Inspired from [CryptoZombies](https://cryptozombies.io/en/lesson/1/chapter/1): 
![image](https://user-images.githubusercontent.com/10279686/80918433-854e7d80-8d82-11ea-9077-4359d7364514.png)

## Contextual help: 
User should be able to provide devs contextual bugs/feedback/conceptual mistakes in each chapter in detail. It would also enable us to make a help section that compounds with each user's doubt. 

### Possible Solutions: 

1. A button that open a form that user can submit details in. 
 * This form sends it to our email. 
 * Can use: https://formspree.io/
 * Complexity: easy for both learner and dev. 
 * Problem: the learner cannot benefit from doubts that get solved. Though this can be solved for once we have a lot of doubts (which is proof of traction)

2. Github template for filing learning issues: and link this to our interface.  
   * Complexity: difficult for learner. 

3. A proper help desk like https://github.com/helpyio/helpy or https://faq.ryanckulp.com/
