### ISSUE TITLE
Website performance optimisation

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#57]
the website should ideally load within 3 seconds at max

Images

- Loading images according to device viewport size

JS bundle

- Lazy loading pages separately

- removing unused code

- minifying JS bundle

- Analyse web-pack for more granular optimisation

**Comment by bhaskarSingh** [comment]
Homepage view is laggy

**Comment by prastut** [comment]
> Homepage view is laggy

Fixed by: https://github.com/buidl-labs/crypto-code-school-inside-tezos/commit/c06e87f56dcece48a696e2d3fd6e8efdddf4666d
