### ISSUE TITLE
Analytics Tracking Consent Tracking

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#81]
Can use: https://klaro.kiprotect.com/

Inspiration from: https://substrate.dev/substrate-contracts-workshop/#/0/setup

**Comment by bhaskarSingh** [comment]
updated copy

![Screenshot 2020-05-05 at 1 09 52 PM](https://user-images.githubusercontent.com/16613455/81044435-f0f33080-8ed1-11ea-9bef-c6489970acab.png)

**Comment by prastut** [comment]
@bhaskarSingh got it! I feel we can further improve. How do I go about editing this directly so that I can iterate on multiple versions of the copy that would make sense for the readers?

**Comment by bhaskarSingh** [comment]
@prastut shared credentials, check your DM.

**Comment by prastut** [comment]
Stale.
