### ISSUE TITLE
Animate characters on the homepage

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#84]
**What's the motivation behind the feature? what problem does the feature intend to solve ?**
Currently, the home page is dull in movement and hence gives a very static feeling. Only the clouds seem to move which are in the background. 

**Describe the solution you'd like.**
Animate the `Plant` and the `Zombie` character in the following image: 

![image](https://user-images.githubusercontent.com/10279686/81035204-9baa2580-8eb7-11ea-803c-a580b45d859d.png)

Possible easy wins: 
1. For `Plant`use the idle animation on https://abhinavthukral97.github.io/CryptoPvZ-Prototype/. Bonus if the plant can even shoot a faint ball. 
2. For `Zombie` use the moving animation but keep the Zombie fixed in one place. 

P.s was inspired by this video: https://www.youtube.com/watch?v=QOChVQEjogI. Probably games incorporate this idle animation to communicate movement.

**Comment by AbhinavThukral97** [comment]
Agreed. For the zombie, a simple bobblehead with swaying arms should be good. If we can incorporate blinking for both that would be brilliant.

**Comment by prastut** [comment]
Stale and non-relevant for Phase 2 of the platform.
