### ISSUE TITLE
Responsive bugs on small screen size laptop

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#91]
I tried this on 2 14'inch screen size laptop (resolution inside a browser: 1263*610). 

Found the following issues: 

## Landing Page
<img width="982" alt="Screenshot 2020-05-08 at 1 46 37 PM" src="https://user-images.githubusercontent.com/10279686/81386795-3d897680-9133-11ea-8b85-e271217a7cca.png">

## Game Intro
<img width="958" alt="Screenshot 2020-05-08 at 1 46 55 PM" src="https://user-images.githubusercontent.com/10279686/81386798-3e220d00-9133-11ea-8aa7-28b601a427a2.png">

- [x] Plants vs Zombies title too big to fit in the header bar. 
- [x] Modal completely bricked

## Learning Interface

<img width="955" alt="Screenshot 2020-05-08 at 1 47 07 PM" src="https://user-images.githubusercontent.com/10279686/81386800-3f533a00-9133-11ea-9dca-8c3338eb65c4.png">

- [ ] Header and footer bar takes too much real estate. Can be made slimmer. 

## Success Modals
<img width="949" alt="Screenshot 2020-05-08 at 1 47 30 PM" src="https://user-images.githubusercontent.com/10279686/81386804-3febd080-9133-11ea-8d4f-0c99018fb3f0.png">

- [x] Modal completely bricked

## Final Battle Page
<img width="914" alt="Screenshot 2020-05-08 at 1 47 56 PM" src="https://user-images.githubusercontent.com/10279686/81386814-437f5780-9133-11ea-840a-710a2a16604a.png">

- [x] Modal completely bricked

**Comment by prastut** [comment]
@bhaskarSingh FYI: 
![image](https://user-images.githubusercontent.com/10279686/81583006-5cf00000-93ce-11ea-9cd5-66a7a0519c30.png)

1. There is a horizontal bar that has come up with the new prod. 
2. There is a weird white overview that has come up in the at the bottom of the content side of things.

**Comment by bhaskarSingh** [comment]
@prastut can you confirm if the learning interface is still overflowing or
not ?

**Comment by prastut** [comment]
@bhaskarSingh 
> @prastut can you confirm if the learning interface is still overflowing or not ?

is the change deployed live?

**Comment by bhaskarSingh** [comment]
> is the change deployed live to prod?

nope, deploying it now

**Comment by prastut** [comment]
Stale and non-relevant for Phase 2 of the platform.
