### ISSUE TITLE
Back button is unintuitive since it goes against obvious human flow

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#92]
Referencing this back button: 
![image](https://user-images.githubusercontent.com/10279686/81387565-8857be00-9134-11ea-9ff2-382a41083f1c.png)

I keep clicking on this assuming to go back to the previous lesson. That's the default pattern which humans are used to. 

Loom does it well as there is no back button: 
![image](https://user-images.githubusercontent.com/10279686/81387723-c5bc4b80-9134-11ea-9c09-53789d461800.png)

**Comment by AbhinavThukral97** [comment]
I agree. We can replace this with a home icon to fix this.

**Comment by prastut** [comment]
Stale and non-relevant for Phase 2 of the platform.
