### ISSUE TITLE
Code Editor Experience Enhancements

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#95]
There are 3 states of the user when they start to move to typing code: 
1. Beginning to code. 
2. Editing code. Contains the following action items: 
   *  While typing -> re-reading `#buidl-ing time` section as to what to do. 
   *  Resetting editor -> if something goes wrong. 
   *  Show/Hide Answer -> if stuck. 
   *  Check Answer -> if finished completing. 
3. Finished coding/chapter experience. 

Some problems noticed with the above states documented below: 

## Beginning to code: 
Ideally the editor to come to light when the user has scrolled to `#buidl-ing time` section. 
A good to have feature, not a huge constraint IMO. 

## Editing code: 
1. Even if my answer is correct, the diff gives me a red error of newline error. Confuses me as is this is something I have to do as well. 
![image](https://user-images.githubusercontent.com/10279686/81525868-aeb76c80-9373-11ea-94e6-f334957493bc.png)

2. Do not show errors if by mistake I edited comments: 
![image](https://user-images.githubusercontent.com/10279686/81532016-58e9c100-9381-11ea-9261-195c9385476c.png)

### Possible solution:  
When typed answer === answer key, then the show answer editor tab should alert with an info telling me about that your answer is correct, proceed to click to checking answer state. 

## Finished coding/chapter experience:
Currently there is no way: 
1. to tell the user at a glance that they finished learning this chapter. See image for reference, for a chapter I finished learning: 
![image](https://user-images.githubusercontent.com/10279686/81525558-bf1b1780-9372-11ea-9cc1-da552beb0617.png)

2. button to re-learn chapter. There is no way to reset a chapter's progress except deleting local storage manually. 

### Possible solution

Ideally there should be a info box with the following: 
1. Info you have already finished. 
2. CTA to relearn chapter if they want to. 
3. with code faded in the background

**Comment by AbhinavThukral97** [comment]
>  editor to come to light 
I suggest we can focus the cursor on the code editor and trigger a simple bounding border highlight animation.

For the part regarding answer checks, I had already mentioned this on slack that comments and extra line spacings should be filtered out prior to the string comparisons.

> When typed answer === answer key, then the show answer editor tab should alert with an info telling me about that your answer is correct, proceed to click to checking answer state.

Not sure how this solution solves the problem, but I like the idea, in general, to accommodate misclicks on Show Answer with an intention to check the code. 

> to tell the user at a glance that they finished learning this chapter

I see two options here:
1. Having an apparent message i.e. either a tag next to the chapter name that says [Completed] or a pop-up on load.
2. A subtle indication by restoring the output console with the success message that is displayed when the chapter is completed. (referring to the completed state of the chapter)

Thoughts? (I prefer the second option)

> button to re-learn chapter. There is no way to reset a chapter's progress except deleting local storage manually.

Actually the reset content editor serves this purpose. 

![image](https://user-images.githubusercontent.com/6816349/82113825-874b1000-9776-11ea-8eaf-20fccf014576.png)

**Comment by prastut** [comment]
@AbhinavThukral97 answered via video (7 mins) since needed visual referencing: https://www.loom.com/share/aca8d3ecb0b74b79ba93cf4d40bda903

**Comment by prastut** [comment]
Stale and non-relevant for Phase 2 of the platform.
