### ISSUE TITLE
Basic Hygiene SEO Ideas

### ISSUE THREAD

**Issue by prastut** [buidl-labs/crypto-code-school-inside-tezos#98]
![image](https://user-images.githubusercontent.com/10279686/81532284-c1d13900-9381-11ea-85f1-2774c698e9fa.png)
![image](https://user-images.githubusercontent.com/10279686/81532336-d6adcc80-9381-11ea-884e-bb858aee217e.png)
![image](https://user-images.githubusercontent.com/10279686/81532389-e9c09c80-9381-11ea-85b1-c9d8ca3937c3.png)

**Comment by prastut** [comment]
## SEO research:

## Netlify side of things: 
https://docs.netlify.com/site-deploys/post-processing/prerendering/#set-up-prerendering

## Using SEO Audit tools:
Why does cryptozombies has 44 crawled pages: 

![image](https://user-images.githubusercontent.com/10279686/81673216-e81dd400-9468-11ea-912c-349e931fac0d.png)

and we have only 1 page: 
![image](https://user-images.githubusercontent.com/10279686/81673270-008dee80-9469-11ea-8158-880261d6f4da.png)

**Comment by bhaskarSingh** [comment]
We actually redirect homepage, to /tezos (That might actually be the cause
of this)

**Comment by prastut** [comment]
-  [ ] Need to add property to this: https://www.google.com/webmasters/tools/crawl-stats?pli=1
-  [ ]  https://www.gatsbyjs.org/tutorial/seo-and-social-sharing-cards-tutorial/ - are we doing everything this tutorial recommends.

**Comment by prastut** [comment]
Merge in #258
